/*
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License version 2 as published by
 *  the Free Software Foundation;
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Library General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */
#ifndef HARDCODED_H
#define HARDCODED_H
#include <qstring.h>

QString USEnglish = //no translation should be done here, it is a layout
"<?xml version=\"1.0\"?>"
"<layout version=\"1.0\" horizgap=\"0.1\" vertgap=\"0.1\" ltr=\"true\">"
"	<row scale=\"1.0\">"
"		<key shape=\"square\" type=\"normal\" homekey=\"false\" size=\"1\" homeindex=\"29\">"
"			<value when=\"rightshift\" draw=\"true\">~</value>"
"			<value when=\"normal\" draw=\"true\" newline=\"true\">`</value>"
"		</key>"
"		<key shape=\"square\" type=\"normal\" homekey=\"false\" size=\"1\" homeindex=\"29\">"
"			<value when=\"rightshift\" draw=\"true\">!</value>"
"			<value when=\"normal\" draw=\"true\" newline=\"true\">1</value>"
"		</key>"
"		<key shape=\"square\" type=\"normal\" homekey=\"false\" size=\"1\" homeindex=\"30\">"
"			<value when=\"rightshift\" draw=\"true\">@</value>"
"			<value when=\"normal\" draw=\"true\" newline=\"true\">2</value>"
"		</key>"
"		<key shape=\"square\" type=\"normal\" homekey=\"false\" size=\"1\" homeindex=\"31\">"
"			<value when=\"rightshift\" draw=\"true\">#</value>"
"			<value when=\"normal\" draw=\"true\" newline=\"true\">3</value>"
"		</key>"
"		<key shape=\"square\" type=\"normal\" homekey=\"false\" size=\"1\" homeindex=\"31\">"
"			<value when=\"rightshift\" draw=\"true\">$</value>"
"			<value when=\"normal\" draw=\"true\" newline=\"true\">4</value>"
"		</key>"
"		<key shape=\"square\" type=\"normal\" homekey=\"false\" size=\"1\" homeindex=\"32\">"
"			<value when=\"rightshift\" draw=\"true\">%</value>"
"			<value when=\"normal\" draw=\"true\" newline=\"true\">5</value>"
"		</key>"
"		<key shape=\"square\" type=\"normal\" homekey=\"false\" size=\"1\" homeindex=\"32\">"
"			<value when=\"rightshift\" draw=\"true\">^</value>"
"			<value when=\"normal\" draw=\"true\" newline=\"true\">6</value>"
"		</key>"
"		<key shape=\"square\" type=\"normal\" homekey=\"false\" size=\"1\" homeindex=\"35\">"
"			<value when=\"leftshift\" draw=\"true\"><![CDATA[&]]></value>"
"			<value when=\"normal\" draw=\"true\" newline=\"true\">7</value>"
"		</key>"
"		<key shape=\"square\" type=\"normal\" homekey=\"false\" size=\"1\" homeindex=\"35\">"
"			<value when=\"leftshift\" draw=\"true\">*</value>"
"			<value when=\"normal\" draw=\"true\" newline=\"true\">8</value>"
"		</key>"
"		<key shape=\"square\" type=\"normal\" homekey=\"false\" size=\"1\" homeindex=\"36\">"
"			<value when=\"leftshift\" draw=\"true\">(</value>"
"			<value when=\"normal\" draw=\"true\" newline=\"true\">9</value>"
"		</key>"
"		<key shape=\"square\" type=\"normal\" homekey=\"false\" size=\"1\" homeindex=\"37\">"
"			<value when=\"leftshift\" draw=\"true\">)</value>"
"			<value when=\"normal\" draw=\"true\" newline=\"true\">0</value>"
"		</key>"
"		<key shape=\"square\" type=\"normal\" homekey=\"false\" size=\"1\" homeindex=\"37\">"
"			<value when=\"leftshift\" draw=\"true\">_</value>"
"			<value when=\"normal\" draw=\"true\" newline=\"true\">-</value>"
"		</key>"
"		<key shape=\"square\" type=\"normal\" homekey=\"false\" size=\"1\" homeindex=\"38\">"
"			<value when=\"leftshift\" draw=\"true\">+</value>"
"			<value when=\"normal\" draw=\"true\" newline=\"true\">=</value>"
"		</key>"
"		<key shape=\"rect\" type=\"backspace\" homekey=\"false\" size=\"2.3;1\">"
"		</key>"		
"	</row>"
"	<row scale=\"1.0\">"
"		<key shape=\"rect\" type=\"tab\" homekey=\"false\" size=\"1.65;1\">"
"		</key>"
"		<key shape=\"square\" type=\"normal\" homekey=\"false\" size=\"1\" homeindex=\"29\">"
"			<value when=\"rightshift\" draw=\"true\">Q</value>"
"			<value when=\"normal\" draw=\"false\">q</value>"
"		</key>"
"		<key shape=\"square\" type=\"normal\" homekey=\"false\" size=\"1\" homeindex=\"30\">"
"			<value when=\"rightshift\" draw=\"true\">W</value>"
"			<value when=\"normal\" draw=\"false\">w</value>"
"		</key>"
"		<key shape=\"square\" type=\"normal\" homekey=\"false\" size=\"1\" homeindex=\"31\">"
"			<value when=\"rightshift\" draw=\"true\">E</value>"
"			<value when=\"normal\" draw=\"false\">e</value>"
"		</key>"
"		<key shape=\"square\" type=\"normal\" homekey=\"false\" size=\"1\" homeindex=\"32\">"
"			<value when=\"rightshift\" draw=\"true\">R</value>"
"			<value when=\"normal\" draw=\"false\">r</value>"
"		</key>"
"		<key shape=\"square\" type=\"normal\" homekey=\"false\" size=\"1\" homeindex=\"32\">"
"			<value when=\"rightshift\" draw=\"true\">T</value>"
"			<value when=\"normal\" draw=\"false\">t</value>"
"		</key>"
"		<key shape=\"square\" type=\"normal\" homekey=\"false\" size=\"1\" homeindex=\"35\">"
"			<value when=\"leftshift\" draw=\"true\">Y</value>"
"			<value when=\"normal\" draw=\"false\">y</value>"
"		</key>"
"		<key shape=\"square\" type=\"normal\" homekey=\"false\" size=\"1\" homeindex=\"35\">"
"			<value when=\"leftshift\" draw=\"true\">U</value>"
"			<value when=\"normal\" draw=\"false\">u</value>"
"		</key>"
"		<key shape=\"square\" type=\"normal\" homekey=\"false\" size=\"1\" homeindex=\"36\">"
"			<value when=\"leftshift\" draw=\"true\">I</value>"
"			<value when=\"normal\" draw=\"false\">i</value>"
"		</key>"
"		<key shape=\"square\" type=\"normal\" homekey=\"false\" size=\"1\" homeindex=\"37\">"
"			<value when=\"leftshift\" draw=\"true\">O</value>"
"			<value when=\"normal\" draw=\"false\">o</value>"
"		</key>"
"		<key shape=\"square\" type=\"normal\" homekey=\"false\" size=\"1\" homeindex=\"38\">"
"			<value when=\"leftshift\" draw=\"true\">P</value>"
"			<value when=\"normal\" draw=\"false\">p</value>"
"		</key>"
"		<key shape=\"square\" type=\"normal\" homekey=\"false\" size=\"1\" homeindex=\"38\">"
"			<value when=\"leftshift\" draw=\"true\">{</value>"
"			<value when=\"normal\" draw=\"true\" newline=\"true\">[</value>"
"		</key>"
"		<key shape=\"square\" type=\"normal\" homekey=\"false\" size=\"1\" homeindex=\"38\">"
"			<value when=\"leftshift\" draw=\"true\">}</value>"
"			<value when=\"normal\" draw=\"true\" newline=\"true\">]</value>"
"		</key>"
"		<key shape=\"rect\" type=\"normal\" homekey=\"false\" size=\"1.65;1\" homeindex=\"38\">"
"			<value when=\"leftshift\" draw=\"true\">|</value>"
"			<value when=\"normal\" draw=\"true\" newline=\"true\">\\</value>"
"		</key>"
"	</row>"
"	<row scale=\"1.0\">"
"		<key shape=\"rect\" type=\"capslock\" homekey=\"false\" size=\"2.1;1\">"
"		</key>"
"		<key shape=\"square\" type=\"normal\" homekey=\"true\" size=\"1\"> 	<!--29-->"
"			<value when=\"rightshift\" draw=\"true\">A</value>"
"			<value when=\"normal\" draw=\"false\">a</value>"
"		</key>"
"		<key shape=\"square\" type=\"normal\" homekey=\"true\" size=\"1\"> 	<!--30-->"
"			<value when=\"rightshift\" draw=\"true\">S</value>"
"			<value when=\"normal\" draw=\"false\">s</value>"
"		</key>"
"		<key shape=\"square\" type=\"normal\" homekey=\"true\" size=\"1\"> 	<!--31-->"
"			<value when=\"rightshift\" draw=\"true\">D</value>"
"			<value when=\"normal\" draw=\"false\">d</value>"
"		</key>"
"		<key shape=\"square\" type=\"normal\" homekey=\"true\" size=\"1\"> 	<!--32-->"
"			<value when=\"rightshift\" draw=\"true\">F</value>"
"			<value when=\"normal\" draw=\"false\">f</value>"
"		</key>"
"		<key shape=\"square\" type=\"normal\" homekey=\"false\" size=\"1\" homeindex=\"32\">"
"			<value when=\"rightshift\" draw=\"true\">G</value>"
"			<value when=\"normal\" draw=\"false\">g</value>"
"		</key>"
"		<key shape=\"square\" type=\"normal\" homekey=\"false\" size=\"1\" homeindex=\"35\">"
"			<value when=\"leftshift\" draw=\"true\">H</value>"
"			<value when=\"normal\" draw=\"false\">h</value>"
"		</key>"
"		<key shape=\"square\" type=\"normal\" homekey=\"true\" size=\"1\"> 	<!--35-->"
"			<value when=\"leftshift\" draw=\"true\">J</value>"
"			<value when=\"normal\" draw=\"false\">j</value>"
"		</key>"
"		<key shape=\"square\" type=\"normal\" homekey=\"true\" size=\"1\"> 	<!--36-->"
"			<value when=\"leftshift\" draw=\"true\">K</value>"
"			<value when=\"normal\" draw=\"false\">k</value>"
"		</key>"
"		<key shape=\"square\" type=\"normal\" homekey=\"true\" size=\"1\"> 	<!--37-->"
"			<value when=\"leftshift\" draw=\"true\">L</value>"
"			<value when=\"normal\" draw=\"false\">l</value>"
"		</key>"
"		<key shape=\"square\" type=\"normal\" homekey=\"true\" size=\"1\"> 	<!--38-->"
"			<value when=\"leftshift\" draw=\"true\">:</value>"
"			<value when=\"normal\" draw=\"true\" newline=\"true\">;</value>"
"		</key>"
"		<key shape=\"square\" type=\"normal\" homekey=\"false\" size=\"1\" homeindex=\"38\">"
"			<value when=\"leftshift\" draw=\"true\">\"</value>"
"			<value when=\"normal\" draw=\"true\" newline=\"true\">'</value>"
"		</key>"
"		<key shape=\"rect\" type=\"enter\" homekey=\"false\" size=\"2.3;1\">"
"		</key>"
"	</row>"
"	<row scale=\"1.0\">"
"		<key shape=\"rect\" type=\"leftshift\" homekey=\"false\" size=\"2.8;1\">"
"		</key>"
"		<key shape=\"square\" type=\"normal\" homekey=\"false\" size=\"1\" homeindex=\"29\">"
"			<value when=\"rightshift\" draw=\"true\">Z</value>"
"			<value when=\"normal\" draw=\"false\">z</value>"
"		</key>"
"		<key shape=\"square\" type=\"normal\" homekey=\"false\" size=\"1\" homeindex=\"30\">"
"			<value when=\"rightshift\" draw=\"true\">X</value>"
"			<value when=\"normal\" draw=\"false\">x</value>"
"		</key>"
"		<key shape=\"square\" type=\"normal\" homekey=\"false\" size=\"1\" homeindex=\"31\">"
"			<value when=\"rightshift\" draw=\"true\">C</value>"
"			<value when=\"normal\" draw=\"false\">c</value>"
"		</key>"
"		<key shape=\"square\" type=\"normal\" homekey=\"false\" size=\"1\" homeindex=\"32\">"
"			<value when=\"rightshift\" draw=\"true\">V</value>"
"			<value when=\"normal\" draw=\"false\">v</value>"
"		</key>"
"		<key shape=\"square\" type=\"normal\" homekey=\"false\" size=\"1\" homeindex=\"32\">"
"			<value when=\"rightshift\" draw=\"true\">B</value>"
"			<value when=\"normal\" draw=\"false\">b</value>"
"		</key>"
"		<key shape=\"square\" type=\"normal\" homekey=\"false\" size=\"1\" homeindex=\"35\">"
"			<value when=\"leftshift\" draw=\"true\">N</value>"
"			<value when=\"normal\" draw=\"false\">n</value>"
"		</key>"
"		<key shape=\"square\" type=\"normal\" homekey=\"false\" size=\"1\" homeindex=\"35\">"
"			<value when=\"leftshift\" draw=\"true\">M</value>"
"			<value when=\"normal\" draw=\"false\">m</value>"
"		</key>"
"		<key shape=\"square\" type=\"normal\" homekey=\"false\" size=\"1\" homeindex=\"36\">"
"			<value when=\"leftshift\" draw=\"true\"><![CDATA[<]]></value>"
"			<value when=\"normal\" draw=\"true\" newline=\"true\">,</value>"
"		</key>"
"		<key shape=\"square\" type=\"normal\" homekey=\"false\" size=\"1\" homeindex=\"37\">"
"			<value when=\"leftshift\" draw=\"true\"><![CDATA[>]]></value>"
"			<value when=\"normal\" draw=\"true\" newline=\"true\">.</value>"
"		</key>"
"		<key shape=\"square\" type=\"normal\" homekey=\"false\" size=\"1\" homeindex=\"38\">"
"			<value when=\"leftshift\" draw=\"true\">?</value>"
"			<value when=\"normal\" draw=\"true\" newline=\"true\">/</value>"
"		</key>"
"		<key shape=\"rect\" type=\"rightshift\" homekey=\"false\" size=\"2.7;1\">"
"		</key>"
"	</row>"
"	<row scale=\"1.0\">"
"		<key shape=\"rect\" type=\"control\" homekey=\"false\" size=\"1.425;1\">"
"		</key>"
"		<key shape=\"rect\" type=\"alt\" homekey=\"false\" size=\"1.425;1\">"
"		</key>"
"		<key shape=\"rect\" type=\"normal\" homekey=\"false\" size=\"10.5;1\">"
"			<value when=\"normal\" draw=\"false\"> </value>"
"		</key>"
"		<key shape=\"rect\" type=\"alt\" homekey=\"false\" size=\"1.425;1\">"
"		</key>"
"		<key shape=\"rect\" type=\"control\" homekey=\"false\" size=\"1.425;1\">"
"		</key>"
"	</row>"
"</layout>";
#endif
